# RECUERDEN NO IGNORAR ESTE ARCHIVO, O NO LES PODREMOS CORREGIR.
DIAS_COMPETENCIA = 6
PROBABILIDAD_ACCIDENTARSE_GIMNASIA = 0.3
# COMPLETAR...

#Parametros deporte:
RIESGO_ATLETISMO = 0.2
RIESGO_CICLISMO = 0.35
RIESGO_GIMNASIA = 0.3
RIESGO_NATACION = 0.25
IMPLEMENTO_ATLETISMO = False
IMPLEMENTO_CICLISMO = True
IMPLEMENTO_GIMNASIA = True
IMPLEMENTO_NATACION = False
NIVEL_IMPLEMENTOS = 1
PUNTAJE_MINIMO = 0.2
VEL_ATL = 0.55
VEL_CIC = 0.47
VEL_GIM = 0.5
VEL_NAT = 0.45
RES_ATL = 0.2
RES_CIC = 0.36
RES_GIM = 0.3
RES_NAT = 0.3
MOR_ATL = 0.25
FLEX_CIC = 0.17
MOR_GIM = 0.2
FLEX_NAT = 0.25

#Parametros delegaciones:
GANA_MED = 0.01
MORALT_MAX = 100
MORALT_MIN = 0
FORTALEZA = 1.0
DEBILIDAD = 0.0
MORAL_EQ = 20
COSTO_ENVIO = 30
MORAL_ENVIO = 1
COSTO_RECUPERACION = 30
SAN_MAX = 1
SAN_MIN = 0
DIV = 200
COSTO_TECNOLOGIA = 20
AUM_IMPLEMENTOS_DEP = 0.1
AUM_IMPLEMENTOS_MED = 0.1
COSTO_HABILIDAD = 20
PON_IEEE = 1.7
MAX_EX_IEEE = 0.8
MIN_EX_IEEE = 0.4
MAX_DEP_IEE = 0.7
MIN_DEP_IEEE = 0.3
MAX_MED_IEEE = 0.6
MIN_MED_IEEE = 0.2
MAX_EX_DCC = 0.7
MIN_EX_DCC = 0.3
MAX_DEP_DCC = 0.6
MIN_DEP_DCC = 0.2
MAX_MED_DCC = 0.8
MIN_MED_DCC = 0.4

#Parametros deportistas:
VELOCIDAD_MAX = 100
VELOCIDAD_MIN = 0
RESISTENCIA_MAX = 100
RESISTENCIA_MIN = 0
FLEXIBILIDAD_MAX = 100
FLEXIBILIDAD_MIN = 0
MORAL_MAX = 100
MORAL_MIN = 0
PUNTOS_ENTRENAMIENTO = 1

#Parametros campeonato:
GANAR_MORAL = 20
PERDER_MORAL = 10
PERDER_EXC_RESP = 0.02
GANAR_DINERO = 100


















